fixup! Add needed for VPN Tile permissions
java.lang.SecurityException: Requires one of the following permissions:
android.permission.NETWORK_STACK,
android.permission.MAINLINE_NETWORK_STACK.

Change-Id: Ie2ab97ae325fdf87e31a88ebf98a476980655be5